apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: maven-image-build
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: |
      body.object_kind == "push"
    pipelinesascode.tekton.dev/pipeline: "https://gitlab-gitlab.apps.cluster-kql8t.dyn.redhatworkshops.io/rhdh/tssc-sample-pipelines/-/raw/main/pipelines/maven-build-ci-simple.yaml"
    pipelinesascode.tekton.dev/task-0: "https://gitlab-gitlab.apps.cluster-kql8t.dyn.redhatworkshops.io/rhdh/tssc-sample-pipelines/-/raw/main/tasks/init.yaml"
    pipelinesascode.tekton.dev/task-1: "https://gitlab-gitlab.apps.cluster-kql8t.dyn.redhatworkshops.io/rhdh/tssc-sample-pipelines/-/raw/main/tasks/git-clone.yaml"
    pipelinesascode.tekton.dev/task-2: "https://gitlab-gitlab.apps.cluster-kql8t.dyn.redhatworkshops.io/rhdh/tssc-sample-pipelines/-/raw/main/tasks/buildah-rhtap.yaml"
    pipelinesascode.tekton.dev/task-3: "https://gitlab-gitlab.apps.cluster-kql8t.dyn.redhatworkshops.io/rhdh/tssc-sample-pipelines/-/raw/main/tasks/acs-image-check.yaml"
    pipelinesascode.tekton.dev/task-4: "https://gitlab-gitlab.apps.cluster-kql8t.dyn.redhatworkshops.io/rhdh/tssc-sample-pipelines/-/raw/main/tasks/acs-image-scan.yaml"
    pipelinesascode.tekton.dev/task-5: "https://gitlab-gitlab.apps.cluster-kql8t.dyn.redhatworkshops.io/rhdh/tssc-sample-pipelines/-/raw/main/tasks/acs-deploy-check.yaml"
    pipelinesascode.tekton.dev/task-6: "https://gitlab-gitlab.apps.cluster-kql8t.dyn.redhatworkshops.io/rhdh/tssc-sample-pipelines/-/raw/main/tasks/update-deployment.yaml"
    pipelinesascode.tekton.dev/task-7: "https://gitlab-gitlab.apps.cluster-kql8t.dyn.redhatworkshops.io/rhdh/tssc-sample-pipelines/-/raw/main/tasks/show-sbom-rhdh.yaml"
    pipelinesascode.tekton.dev/task-8: "https://gitlab-gitlab.apps.cluster-kql8t.dyn.redhatworkshops.io/rhdh/tssc-sample-pipelines/-/raw/main/tasks/summary.yaml"
    pipelinesascode.tekton.dev/task-9: "https://gitlab-gitlab.apps.cluster-kql8t.dyn.redhatworkshops.io/rhdh/tssc-sample-pipelines/-/raw/main/tasks/maven.yaml"
    pipelinesascode.tekton.dev/task-10: "https://gitlab-gitlab.apps.cluster-kql8t.dyn.redhatworkshops.io/rhdh/tssc-sample-pipelines/-/raw/main/tasks/upload-sbom-to-trustification.yaml"
    pipelinesascode.tekton.dev/task-11: "https://gitlab-gitlab.apps.cluster-kql8t.dyn.redhatworkshops.io/rhdh/tssc-sample-pipelines/-/raw/main/tasks/verify-commit.yaml"
    pipelinesascode.tekton.dev/task-12: "https://gitlab-gitlab.apps.cluster-kql8t.dyn.redhatworkshops.io/rhdh/tssc-sample-pipelines/-/raw/main/tasks/maven-21.yaml"
  labels:
    backstage.io/kubernetes-id: "platformcon-api"
spec:
  params:
    - name: component-name
      value: platformcon-api
    - name: dockerfile
      value: ./Dockerfile
    - name: git-url
      value: '{{repo_url}}'
    - name: image-expires-after
      value: 5d
    - name: output-image
      value: "quay-kql8t-1.apps.cluster-kql8t.dyn.redhatworkshops.io/tssc/platformcon-api:{{revision}}"
    - name: path-context
      value: ./
    - name: revision
      value: '{{revision}}'
    - name: event-type
      value: '{{event_type}}'
  pipelineRef:
    name: maven-build-ci-simple
  workspaces:
    - name: gitops-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: maven-settings
      emptyDir: {}
    - name: maven-cache
      persistentVolumeClaim:
        claimName: maven-cache-pvc2
